"""connection refresh token

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 10:50:50.140690
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_refresh_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_connections', schema=None) as batch_op:
        batch_op.drop_column('encrypted_refresh_token')

    # ### end Alembic commands ###
