"""monitoring and alerts

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 12:48:13.102000
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('standing_approvals', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('scoring_weights', sa.JSON(), nullable=False),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('notify_emails', sa.JSON(), nullable=False),
    sa.Column('encrypted_webhook_url', sa.Text(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.String(length=40), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitors_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitors_org_id'), ['org_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('monitor_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('notifications', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'kind')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_run_id'), ['run_id'], unique=False)

    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('baseline_run_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('changes', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_analysis_runs_monitor_id'), ['monitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_monitor_id'))
        batch_op.drop_column('changes')
        batch_op.drop_column('baseline_run_id')
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_run_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_project_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_org_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitors_org_id'))
        batch_op.drop_index(batch_op.f('ix_monitors_next_run_at'))

    op.drop_table('monitors')
    # ### end Alembic commands ###
