"""knowledge base

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 10:22:28.368895
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('outcomes', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.String(length=300), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('project_types', sa.JSON(), nullable=False),
    sa.Column('capability_tags', sa.JSON(), nullable=False),
    sa.Column('ai', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('automation', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('linked_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('reference_allowed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_records_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_records_status'), ['status'], unique=False)

    op.create_table('knowledge_record_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.String(length=40), nullable=True),
    sa.Column('changed_by_email', sa.String(length=320), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['knowledge_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'version')
    )
    with op.batch_alter_table('knowledge_record_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_record_versions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_record_versions_record_id'), ['record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_record_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_record_versions_record_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_record_versions_org_id'))

    op.drop_table('knowledge_record_versions')
    with op.batch_alter_table('knowledge_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_records_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_records_org_id'))

    op.drop_table('knowledge_records')
    # ### end Alembic commands ###
