"""sales documents

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-08 10:37:12.793246
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('generated', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'kind')
    )
    with op.batch_alter_table('sales_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_documents_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_documents_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_documents_run_id'))
        batch_op.drop_index(batch_op.f('ix_sales_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_sales_documents_org_id'))

    op.drop_table('sales_documents')
    # ### end Alembic commands ###
