"""run versions

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-08 11:23:07.267281
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_run_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('rerun_stages', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_column('rerun_stages')
        batch_op.drop_column('parent_run_id')

    # ### end Alembic commands ###
