"""review overrides

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-08 11:36:32.840757
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_overrides',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('target_label', sa.String(length=300), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_run_id', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_by_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'kind', 'target_id', 'field')
    )
    with op.batch_alter_table('review_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_overrides_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_overrides_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_overrides_run_id'))
        batch_op.drop_index(batch_op.f('ix_review_overrides_org_id'))

    op.drop_table('review_overrides')
    # ### end Alembic commands ###
